### ISSUE TITLE
Homebrew vtk is Python3.9 per default

### ISSUE THREAD

**Issue by eramoisi** [ULB-Metronu/homebrew-metronu#3]
Homebrew vtk is Python3.9 per default which induces contradictions with our formulas that require python3.8 -> problem in the BDSIM compilation

**Comment by rtesse** [comment]
Indeed, vtk requires Python@3.9 to work. At the moment, we would like to stay with Python@3.8. Therefore, I created a vtk recipe using python@3.8 and updated bdsim.rb and geant4.rb.

**Comment by eramoisi** [comment]
The installation using python@3.8 works at the condition to install vtk with the option "--build-from-source" before installing geant4.
